---
- name: Install Nginx Web Server
  hosts: servers
  become: yes
  tasks:
    - name: Install nginx based authentication on Ubuntu
      apt:
        name: nginx
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


  tasks:
    - name: Install nginx based authentication on Ubuntu
      dnf:
        name: nginx
        state: latest
      when: ansible_distribution == 'Amazon' or ansible_distribution == 'RedHat'    
